[features]
seeds = false
[programs.localnet]
solana_twitter = "5tH6RaLcV3Wq3whjLoVwnYWx6rvSnSDSC7FTUJv4yMTy"


[programs.devnet]
solana_twitter = "5tH6RaLcV3Wq3whjLoVwnYWx6rvSnSDSC7FTUJv4yMTy"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/zunairajaved/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
